### ISSUE TITLE
Built-in datasets: Convert fails

### ISSUE THREAD

**Issue by act65** [mila-udem/fuel#341]
Hey,

I just started playing with this (good work btw).
I have managed to sort out/get working the mnist, cifar10, and silhouette datasets. However, the rest seem to give me some sort of error when I try to convert them, after downloading.

For example I get;

> Traceback (most recent call last):
  File "/Users/act65/anaconda/bin/fuel-convert", line 9, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/bin/fuel_convert.py", line 76, in main
    output_paths = convert_function(**args_dict)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/adult.py", line 60, in convert_adult
    output_path = os.path.join(output_directory, output_filename)
  File "/Users/act65/anaconda/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/act65/anaconda/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

 when I try `fuel-convert adult`
and
> Traceback (most recent call last):
  File "/Users/act65/anaconda/bin/fuel-convert", line 9, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/bin/fuel_convert.py", line 76, in main
    output_paths = convert_function(**args_dict)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 198, in convert_celeba
    directory, output_directory, output_filename)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/base.py", line 45, in wrapped
    return f(directory, *args, **kwargs)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 139, in convert_celeba_64
    h5file = _initialize_conversion(directory, output_path, (64, 64))
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 41, in _initialize_conversion
    skiprows=2, usecols=tuple(range(1, 41))) +
  File "/Users/act65/anaconda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 921, in loadtxt
    vals = [vals[i] for i in usecols]
  File "/Users/act65/anaconda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 921, in <listcomp>
    vals = [vals[i] for i in usecols]
IndexError: list index out of range

 when I try `fuel-convert celeba 64`

Help??

Also, what are your guys plans for adding more data sets? I wouldnt mind a bit more diversity, eg sequences, audio, even something more exotic like DNA?? I wrote a downloader for some jane austen books, so ill see if i can get those working in the converter although i am sure that is tricky.

**Comment by bartvm** [comment]
Please update your Fuel installation, I believe this was fixed yesterday.

**Comment by act65** [comment]
Ok,

it worked for adult and iris. 

still not working for celeba and others?

e.g. i get

> Traceback (most recent call last):
  File "/Users/act65/anaconda/bin/fuel-convert", line 9, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/bin/fuel_convert.py", line 79, in main
    output_paths = convert_function(**args_dict)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/svhn.py", line 365, in convert_svhn
    directory, output_directory, output_filename)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/base.py", line 45, in wrapped
    return f(directory, *args, **kwargs)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/svhn.py", line 109, in convert_svhn_format_1
    [(split, extract_tar(split)) for split in splits])
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/svhn.py", line 109, in <listcomp>
    [(split, extract_tar(split)) for split in splits])
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/svhn.py", line 97, in extract_tar
    members = f.getmembers()
  File "/Users/act65/anaconda/lib/python3.5/tarfile.py", line 1752, in getmembers
    self._load()        # all members, we first have to
  File "/Users/act65/anaconda/lib/python3.5/tarfile.py", line 2344, in _load
    tarinfo = self.next()
  File "/Users/act65/anaconda/lib/python3.5/tarfile.py", line 2275, in next
    self.fileobj.seek(self.offset - 1)
  File "/Users/act65/anaconda/lib/python3.5/gzip.py", line 366, in seek
    return self._buffer.seek(offset, whence)
  File "/Users/act65/anaconda/lib/python3.5/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/Users/act65/anaconda/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

for `fuel-convert svhn 1`

and 

> Traceback (most recent call last):
  File "/Users/act65/anaconda/bin/fuel-convert", line 9, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/bin/fuel_convert.py", line 79, in main
    output_paths = convert_function(**args_dict)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 198, in convert_celeba
    directory, output_directory, output_filename)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/base.py", line 45, in wrapped
    return f(directory, *args, **kwargs)
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 139, in convert_celeba_64
    h5file = _initialize_conversion(directory, output_path, (64, 64))
  File "/Users/act65/anaconda/lib/python3.5/site-packages/fuel-0.2.0-py3.5-macosx-10.5-x86_64.egg/fuel/converters/celeba.py", line 41, in _initialize_conversion
    skiprows=2, usecols=tuple(range(1, 41))) +
  File "/Users/act65/anaconda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 921, in loadtxt
    vals = [vals[i] for i in usecols]
  File "/Users/act65/anaconda/lib/python3.5/site-packages/numpy/lib/npyio.py", line 921, in <listcomp>
    vals = [vals[i] for i in usecols]
IndexError: list index out of range

for `fuel-convert celeba 64`

**Comment by BrianWestlake** [comment]
Not sure why this was closed when it still seems to be an unsolved problem. I am also getting this outcome

```
Traceback (most recent call last):
  File "/usr/local/bin/fuel-convert", line 11, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/usr/local/lib/python2.7/dist-packages/fuel/bin/fuel_convert.py", line 79, in main
    output_paths = convert_function(**args_dict)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 198, in convert_celeba
    directory, output_directory, output_filename)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/base.py", line 45, in wrapped
    return f(directory, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 139, in convert_celeba_64
    h5file = _initialize_conversion(directory, output_path, (64, 64))
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 41, in _initialize_conversion
    skiprows=2, usecols=tuple(range(1, 41))) +
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 923, in loadtxt
    vals = [vals[i] for i in usecols]
IndexError: list index out of range
```
This is with the latest versions of Theano, Blocks and Fuel
